const routes = {
  home: '/',
  authors: '/authors',
  explore: '/explore',
  products: '/products',
  shops: '/shops',
  popularProducts: '/popular-products',
  about: '/about-us',
  contact: '/contact-us',
  purchases: '/purchases',
  wishlists: '/wishlists',
  reports: '/reports',
  questions: '/questions',
  profile: '/profile',
  checkout: '/checkout',
  help: '/help',
  return: '/help/return',
  marketplace: '/marketplace',
  earn: '/earn',
  licensing: '/licensing',
  refund: '/refund',
  terms: '/terms',
  privacy: '/privacy',
  password: '/password',
  feed: '/feed',
  placesFeed: '/places',
  wallet: '/wallet',
  followedShop: '/followed-authors',
  chat: '/chat',
  orderUrl: (tracking_number: string) =>
    `/orders/${encodeURIComponent(tracking_number)}`,
  productUrl: (slug: string) => `/products/${slug}`,
  categoryUrl: (slug: string) => `/categories/${slug}`,
  tagUrl: (slug: string) => `/products/tags/${slug}`,
  placeHashtagUrl: (slug: string) => `/places/element/${slug}`,
  shopUrl: (slug: string) => `/authors/${slug}`,
  product: (slug: string) => {
    return `/products/${encodeURIComponent(slug)}`;
  },
  cards: '/cards',
  telegram: 'https://t.me/sancan_seller',

  art: '/?category=art',
  tovarydoma: '/?category=tovary-dlya-doma',
  mebel: '/?category=mebel',
  interer: '/?category=dom-i-interer',
  fashion: '/?category=fashion',
  handmade: '/?category=handmade',
  hobbi: '/?category=hobbi-i-tvorchestvo',
  ukrasheniya: '/?category=ukrasheniya',
  seller: 'https://seller.sancan.ru/register',


};
export default routes;
